services:
  api:
    build:
      context: ./JudgeAPI
      dockerfile: Dockerfile.dev
    ports:
      - "5000:8080"
    volumes:
      - ./JudgeAPI:/app
    env_file:
      - .env.local
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "1"
    depends_on:
      - db
      - redis

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports: ["14330:1433"]
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
    volumes:
      - redisdata:/data

  runner:
    user: root
    build:
      context: .
      dockerfile: RunnerApp/Dockerfile
    environment:
      HOST_JOBS_DIR: ${PWD}/jobs
    volumes:
      - ./jobs:/app/jobs
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.local
    depends_on:
      - redis
      - db

  cpp-runner-image:
    build:
      context: ./JudgeAPI/CppRunnerImage
    image: judge-cpp-runner
    volumes:
      - ./jobs:/app/jobs

volumes:
  sqlvolume:
  redisdata:
