version: '3.8'

services:
  api:
    volumes:
      - ./JudgeAPI:/app
    working_dir: /app
    command: sh -c "dotnet watch run --urls=http://0.0.0.0:80"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
    ports:
      - "5000:80"
