services:
  api:
    build:
      context: ./JudgeAPI
    ports:
      - "5500:8080"
    command: dotnet run
    depends_on:
      - db
    env_file:
      - .env
    restart: unless-stopped

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD}
      ACCEPT_EULA: "Y"
    volumes:
      - sqlvolume:/var/opt/mssql
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redisdata:/data
    restart: unless-stopped

  runner:
    user: root
    build:
      context: .
      dockerfile: RunnerApp/Dockerfile
    volumes:
      - jobsdata:/app/jobs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  sqlvolume:
  redisdata:
  jobsdata:
